- name: Set up and run Docker containers
  hosts: all
  become: true
  tasks:
    - name: Deploy service
      ansible.builtin.include_role:
        name: docker
        tasks_from: deploy.yml
      loop: "{{ docker_services }}"
      loop_control:
        loop_var: service
