---
- name: Install firewalld
  ansible.builtin.apt:
    package: firewalld
    state: present

- name: Set default zone to public
  ansible.builtin.command: firewall-cmd --set-default-zone=public
  register: firewalld_default_zone_set
  changed_when:
    - '"ZONE_ALREADY_SET" not in firewalld_default_zone_set.stderr'

- name: Disable forwarding
  ansible.posix.firewalld:
    zone: public
    state: enabled
    forward: false
    permanent: true

- name: Allow SSH traffic
  ansible.posix.firewalld:
    zone: public
    service: ssh
    state: enabled
    permanent: true

- name: Reload config
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  notify: Enable and start firewalld
