- name: Check if firewalld is running
  ansible.builtin.systemd:
    name: firewalld
  register: firewalld_service

- name: Open ports if active
  when: firewalld_service.status.ActiveState == "active"
  block:
    - name: Open SMB
      ansible.posix.firewalld:
        zone: public
        service: samba
        state: enabled
        permanent: true
      notify: Reload firewalld config
