# Configuration managed by Ansible

# Disallow logging in as root, no password login by default
PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
AuthenticationMethods publickey
MaxAuthTries 3
